services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      timeout: 20s
      retries: 10
      interval: 20s
      start_period: 30s

  notification-mservice:
    build: .
    container_name: notification-mservice-container
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FIREBASE_CREDENTIALS_JSON: ${FIREBASE_CREDENTIALS_JSON}
    ports:
      - "${NOTIFICATION_MSERVICE_HTTP_PORT}:${NOTIFICATION_MSERVICE_HTTP_PORT}"
      - "${NOTIFICATION_MSERVICE_GRPC_PORT}:${NOTIFICATION_MSERVICE_GRPC_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    driver: "bridge"

volumes:
  postgres_data:
    driver: local
