sonar.projectKey=sw5005-sus_ceramicraft-notification-mservice
sonar.organization=sw5005-sus
sonar.projectName=ceramicraft-notification-mservice

sonar.sources=src/ceramicraft_notification_mservice
sonar.tests=tests
sonar.exclusions=src/ceramicraft_notification_mservice/pb/**,src/ceramicraft_notification_mservice/http/static/**
sonar.test.exclusions=**/pb/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
